# Generated by Django 5.2.17 on 2026-08-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0002_flyeritem_and_more'),
        ('offers', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBranchAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited Stock'), ('UNAVAILABLE', 'Out of Stock'), ('UNKNOWN', 'Availability Not Confirmed')], default='UNKNOWN', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['branch', 'offer'],
            },
        ),
        migrations.RemoveIndex(
            model_name='offer',
            name='offers_offe_store_b_99727d_idx',
        ),
        migrations.AddField(
            model_name='offer',
            name='flyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='flyers.flyer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='flyer_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='flyers.flyerpage'),
        ),
        migrations.AddField(
            model_name='offer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], db_index=True, default='PUBLISHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='store_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='stores.storebranch'),
        ),
        migrations.AddField(
            model_name='offerbranchavailability',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_availabilities', to='stores.storebranch'),
        ),
        migrations.AddField(
            model_name='offerbranchavailability',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availabilities', to='offers.offer'),
        ),
        migrations.AlterUniqueTogether(
            name='offerbranchavailability',
            unique_together={('offer', 'branch')},
        ),
    ]
