# Generated by Django 5.2.17 on 2026-08-14 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('cover_image_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('pdf_url', models.URLField()),
                ('page_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flyers', to='stores.storebranch')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FlyerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('image_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='flyers.flyer')),
            ],
            options={
                'ordering': ['flyer', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='FlyerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('position_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='flyers.flyer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'ordering': ['flyer', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='FlyerView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('flyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='flyers.flyer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='flyer',
            index=models.Index(fields=['store_branch', 'status'], name='flyers_flye_store_b_549f49_idx'),
        ),
        migrations.AddIndex(
            model_name='flyer',
            index=models.Index(fields=['start_date', 'end_date', 'status'], name='flyers_flye_start_d_dbc7c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flyerpage',
            unique_together={('flyer', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='flyerview',
            index=models.Index(fields=['flyer', 'viewed_at'], name='flyers_flye_flyer_i_0305aa_idx'),
        ),
    ]
