# Generated by Django 5.2.17 on 2026-08-14 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('flyers', '0001_initial'),
        ('offers', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['flyer_page', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='flyer',
            name='flyers_flye_store_b_549f49_idx',
        ),
        migrations.RemoveIndex(
            model_name='flyer',
            name='flyers_flye_start_d_dbc7c8_idx',
        ),
        migrations.AddField(
            model_name='flyer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_flyers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flyer',
            name='online_shopping_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
        migrations.AddField(
            model_name='flyer',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyers', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flyers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('PENDING_REVIEW', 'Pending Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='store_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyers', to='stores.storebranch'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flyerpage',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='flyer',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='flyers_flye_status_523c35_idx'),
        ),
        migrations.AddIndex(
            model_name='flyer',
            index=models.Index(fields=['store', 'status'], name='flyers_flye_store_i_6edd00_idx'),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='flyer_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='flyers.flyerpage'),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flyer_items', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flyer_items', to='catalog.product'),
        ),
    ]
