# Generated by Django 5.2.17 on 2026-08-15 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('flyers', '0002_flyeritem_and_more'),
        ('stores', '0002_store_address_store_approved_at_store_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='multi_flyers', to='stores.storebranch'),
        ),
        migrations.AddField(
            model_name='flyer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flyers', to='catalog.category'),
        ),
    ]
