# Generated by Django 5.2.17 on 2026-08-15 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0003_flyer_branches_flyer_category'),
        ('stores', '0003_storebranch_location_url_alter_storebranch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyeritem',
            name='store_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flyer_items', to='stores.storebranch'),
        ),
    ]
