# Generated by Django 5.2.17 on 2026-08-15 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0004_flyeritem_store_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flyeritem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='flyer',
            name='image_height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='image_width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flyer',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='bbox_h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='bbox_w',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='bbox_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='bbox_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='deal_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='deal_type',
            field=models.CharField(blank=True, default='flat_discount', max_length=50),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='flyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_items', to='flyers.flyer'),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='item_category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flyeritem',
            name='flyer_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='flyers.flyerpage'),
        ),
        migrations.AlterField(
            model_name='flyeritem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
