# Generated by Django 5.2.17 on 2026-08-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0005_alter_flyeritem_options_flyer_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='category_slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flyer',
            name='store_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='col_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='row_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flyerpage',
            name='image_height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flyerpage',
            name='image_width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
