# Generated by Django 5.2.17 on 2026-08-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0006_flyer_category_slug_flyer_store_logo_url_and_more'),
        ('stores', '0003_storebranch_location_url_alter_storebranch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyeritem',
            name='available_branches',
            field=models.ManyToManyField(blank=True, related_name='item_flyer_items', to='stores.storebranch'),
        ),
    ]
